" https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" Enable plugins
call plug#begin('~/.vim/plugged')

Plug 'michaeljsmith/vim-indent-object'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/vim-easy-align'
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'
"Plug 'edkolev/tmuxline.vim'
"Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}
"Plug 'honza/vim-snippets'
Plug 'ryanoasis/vim-devicons'
"Plug 'SirVer/ultisnips'
Plug 'christoomey/vim-tmux-navigator'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" Colorschemes
Plug 'KeitaNakamura/neodark.vim'
Plug 'joshdick/onedark.vim'
Plug 'rakr/vim-one'
Plug 'junegunn/seoul256.vim'

call plug#end()



" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

filetype on 		" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype plugin on 	" Enable plugins and load plugin for the detected file type.
filetype indent on 	" Load an indent file for the detected file type.

" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Highlight cursor line underneath the cursor vertically.
set cursorcolumn

" Ignore capital letters during search.
set ignorecase

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

set showcmd
set cmdheight=1

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs

" tab parameters
set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab

""" Turn on color theme

" Dracula theme
"packadd! dracula_pro
"let g:dracula_colorterm = 0
"let g:dracula_italic = 0
"colorscheme dracula_pro_lincoln

" neodark theme
let g:neodark#background = '#2C2A21'
let g:neodark#background = '#202020'
let g:airline_theme='onedark'
colorscheme neodark

" Seoul245 theme
"let g:seoul256_background = 233
"let g:seoul256_light_background = 256
"let g:airline_theme='onedark'
"colorscheme seoul256


""" air-line
let g:airline_powerline_fonts=1
let g:bufferline_echo = 0


